[package]
name = "services"
version = "0.1.0"
edition = "2024"

[dependencies]
helpers = { path = "../helpers" }
models = { path = "../models" }
rocket.workspace = true
diesel.workspace = true
diesel-async.workspace = true
